In [1]:
def create_deck():
    deck = []
    seeds = 'S C H D'.split()
    values = [str(x) for x in range(2, 11)] + ['A', 'J', 'Q', 'K']
    for value in values:
        for seed in seeds:
            deck.append((value, seed))
    return deck

In [2]:
def create_simple_deck():
    deck = []
    seeds = 'S C H D'.split()
    values = [str(x) for x in range(2, 8)] + ['A', 'J', 'Q', 'K']
    for value in values:
        for seed in seeds:
            deck.append((value, seed))
    return deck

In [3]:
seeds = 'S C H D'.split()
seeds

['S', 'C', 'H', 'D']

In [4]:
values = [str(x) for x in range(2, 11)] + ['A', 'J', 'Q', 'K']
values

['2', '3', '4', '5', '6', '7', '8', '9', '10', 'A', 'J', 'Q', 'K']

In [5]:
deck = []
for value in values:
        for seed in seeds:
            deck.append((value, seed))
deck

[('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('8', 'S'),
 ('8', 'C'),
 ('8', 'H'),
 ('8', 'D'),
 ('9', 'S'),
 ('9', 'C'),
 ('9', 'H'),
 ('9', 'D'),
 ('10', 'S'),
 ('10', 'C'),
 ('10', 'H'),
 ('10', 'D'),
 ('A', 'S'),
 ('A', 'C'),
 ('A', 'H'),
 ('A', 'D'),
 ('J', 'S'),
 ('J', 'C'),
 ('J', 'H'),
 ('J', 'D'),
 ('Q', 'S'),
 ('Q', 'C'),
 ('Q', 'H'),
 ('Q', 'D'),
 ('K', 'S'),
 ('K', 'C'),
 ('K', 'H'),
 ('K', 'D')]

In [6]:
def create_decks(n_decks = 1, hello): # if, when calling the function, n_decks is not specified, 1 deck is created
                                      # if the function has more than 1 argument, default values must be specified
                                      # either for all arguments or arguments without a default value must be put
                                      # at the beginning
    print(hello)
    decks = []
    for i in range(n_decks):
        deck = create_deck()
        decks.extend(deck) # 'append' would create a list of lists; we want 1 list with cards from n decks
    return decks

SyntaxError: parameter without a default follows parameter with a default (3421634360.py, line 1)

In [7]:
def create_decks(n_decks:int): # ':int' is not a formal constraint; it's more of a comment
    decks = []
    for i in range(n_decks):
        deck = create_deck()
        decks.extend(deck) # 'append' would create a list of lists; we want 1 list with cards from n decks
    return decks

In [8]:
my_decks = create_decks(2)
my_decks

[('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('8', 'S'),
 ('8', 'C'),
 ('8', 'H'),
 ('8', 'D'),
 ('9', 'S'),
 ('9', 'C'),
 ('9', 'H'),
 ('9', 'D'),
 ('10', 'S'),
 ('10', 'C'),
 ('10', 'H'),
 ('10', 'D'),
 ('A', 'S'),
 ('A', 'C'),
 ('A', 'H'),
 ('A', 'D'),
 ('J', 'S'),
 ('J', 'C'),
 ('J', 'H'),
 ('J', 'D'),
 ('Q', 'S'),
 ('Q', 'C'),
 ('Q', 'H'),
 ('Q', 'D'),
 ('K', 'S'),
 ('K', 'C'),
 ('K', 'H'),
 ('K', 'D'),
 ('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('8', '

In [9]:
print(len(my_decks))

104


In [10]:
def create_simple_or_regular_decks(n_decks = 1, deck_generator = create_deck):
                                            # passing function as an argument; default function is 'create_deck'
    decks = []
    for i in range(n_decks):
        deck = deck_generator()
        decks.extend(deck)
    return decks

In [11]:
create_simple_or_regular_decks(n_decks = 2, deck_generator = create_simple_deck)

[('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('A', 'S'),
 ('A', 'C'),
 ('A', 'H'),
 ('A', 'D'),
 ('J', 'S'),
 ('J', 'C'),
 ('J', 'H'),
 ('J', 'D'),
 ('Q', 'S'),
 ('Q', 'C'),
 ('Q', 'H'),
 ('Q', 'D'),
 ('K', 'S'),
 ('K', 'C'),
 ('K', 'H'),
 ('K', 'D'),
 ('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('A', 'S'),
 ('A', 'C'),
 ('A', 'H'),
 ('A', 'D'),
 ('J', 'S'),
 ('J', 'C'),
 ('J', 'H'),
 ('J', 'D'),
 ('Q', 'S'),
 ('Q', 'C'),
 ('Q', 'H'),
 ('Q', 'D'),
 ('K', 'S'),

In [12]:
n, f = 4, create_simple_deck
my_deck = create_simple_or_regular_decks(n_decks = n, deck_generator = f)
assert len(my_deck) == n*40 # if it's TRUE, no output

In [13]:
age = {
    'p1': 23,
    'p2': 24
}

In [14]:
for key, value in age.items():
    print(key, value)

p1 23
p2 24


In [15]:
list(age.keys())

['p1', 'p2']

In [16]:
list(age.values())

[23, 24]

In [17]:
card_value = {
    'A': 11,
    'J': 10,
    'Q': 10,
    'K': 10
}
card_value

{'A': 11, 'J': 10, 'Q': 10, 'K': 10}

In [18]:
def get_card_value(x):
    if x in card_value.keys():
        return card_value[x]
    else:
        return int(x)

In [19]:
get_card_value('A')

11

In [20]:
def get_card_value1(x):
    try:
        return card_value[x]
    except KeyError:
        return int(x)

In [21]:
get_card_value1('A')

11

In [22]:
def get_card_value2(x):
    return card_value.get(x, int(x))
# 'get' function allows to specify a default value in case the key is not in the dictionary

In [23]:
get_card_value2('A')

ValueError: invalid literal for int() with base 10: 'A'

In [ ]:
def get_card_value3(x):
    surface = x[0]
    if surface in {'J', 'K', 'Q'}:
        return 10
    elif surface == 'A':
        return 11
    else:
        return int(surface)


In [24]:
def as_str(x):
    return "{}{}".format(x[0], x[1])

In [25]:
my_deck1 = create_deck()
my_deck1

[('2', 'S'),
 ('2', 'C'),
 ('2', 'H'),
 ('2', 'D'),
 ('3', 'S'),
 ('3', 'C'),
 ('3', 'H'),
 ('3', 'D'),
 ('4', 'S'),
 ('4', 'C'),
 ('4', 'H'),
 ('4', 'D'),
 ('5', 'S'),
 ('5', 'C'),
 ('5', 'H'),
 ('5', 'D'),
 ('6', 'S'),
 ('6', 'C'),
 ('6', 'H'),
 ('6', 'D'),
 ('7', 'S'),
 ('7', 'C'),
 ('7', 'H'),
 ('7', 'D'),
 ('8', 'S'),
 ('8', 'C'),
 ('8', 'H'),
 ('8', 'D'),
 ('9', 'S'),
 ('9', 'C'),
 ('9', 'H'),
 ('9', 'D'),
 ('10', 'S'),
 ('10', 'C'),
 ('10', 'H'),
 ('10', 'D'),
 ('A', 'S'),
 ('A', 'C'),
 ('A', 'H'),
 ('A', 'D'),
 ('J', 'S'),
 ('J', 'C'),
 ('J', 'H'),
 ('J', 'D'),
 ('Q', 'S'),
 ('Q', 'C'),
 ('Q', 'H'),
 ('Q', 'D'),
 ('K', 'S'),
 ('K', 'C'),
 ('K', 'H'),
 ('K', 'D')]

In [26]:
for card in my_deck1:
    print(as_str(card), "==>", get_card_value3(card))

NameError: name 'get_card_value3' is not defined

In [27]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8]
np.random.shuffle(a) # doesn't create a new, shuffled list, but shuffles 'a'
a

[3, 4, 1, 2, 6, 8, 5, 7]

In [28]:
a.pop() # returns the last item of 'a'
a.pop(0) # returnd the first item of 'a'

3

In [29]:
np.random.choice(a, size = 6, replace = True, p = [.8, .1, .1, 0, 0, 0, 0, 0])

ValueError: 'a' and 'p' must have same size

In [30]:
b = np.array(a)
b

array([4, 1, 2, 6, 8, 5])

In [31]:
b.shape # or len(b)

(6,)

In [32]:
3 * b

array([12,  3,  6, 18, 24, 15])

In [33]:
m = np.array([
    [2, 3, 4],
    [1, 2, 2]
])
m

array([[2, 3, 4],
       [1, 2, 2]])

In [34]:
c = b.reshape(2, 3) # creates a 2x4 matrix out of vector 'b'
c

array([[4, 1, 2],
       [6, 8, 5]])

In [35]:
b.reshape(2, -1) # '-1' means that Python chooses the number of columns s.t. all numbers are distributed

array([[4, 1, 2],
       [6, 8, 5]])

In [36]:
d = b.reshape(-1, 2)
d

array([[4, 1],
       [2, 6],
       [8, 5]])

In [37]:
np.random.choice(a, size = (3, 6), replace = True, p = [.8, .1, .1, 0, 0, 0, 0, 0])

ValueError: 'a' and 'p' must have same size

In [38]:
c[0]

array([4, 1, 2])

In [39]:
d[-2:, -1:]

array([[6],
       [5]])

In [40]:
d.T

array([[4, 2, 8],
       [1, 6, 5]])

In [41]:
d

array([[4, 1],
       [2, 6],
       [8, 5]])

In [42]:
d[:, 0].mean() # also std(), sum(), prod()

4.666666666666667

In [43]:
d.mean() # mean of all the elements in the matrix

4.333333333333333

In [44]:
d.mean(axis = 0) # '0' -> column-wise mean
d.mean(axis = 1) # '1' -> row-wise mean

array([2.5, 4. , 6.5])

In [45]:
X = np.random.randint(0, 10, size = (3, 2))
X

array([[9, 4],
       [0, 5],
       [8, 1]])

In [46]:
d * X # element-wise multiplication

array([[36,  4],
       [ 0, 30],
       [64,  5]])

In [47]:
d.T.dot(X) # dot product

array([[100,  34],
       [ 49,  39]])

In [156]:
class Card:
    def __init__(self, surface, seed):
        self.surface = surface
        self.seed = seed

    def __str__(self):
        return "{} {}".format(self.surface, self.seed)
    
    def __repr__(self):
        return str(self)

    @property
    def value(self):
        if self.surface in {'J', 'Q', 'K'}:
            return 10
        elif self.surface == 'A':
            return 1
        else:
            return int(self.surface)

In [126]:
c = Card('A', 'H')
c

A H

In [127]:
c.surface, c.seed

('A', 'H')

In [128]:
c.__str__()

'A H'

In [129]:
surfaces = [str(x) for x in range(2, 11)] + ['A', 'J', 'Q', 'K']
seeds = 'S C H D'.split()

for surface in surfaces:
    for seed in seeds:
        c = Card(surface = surface, seed = seed)
        print(c.__str__(), "==>", c.value())

2 S ==> 2
2 C ==> 2
2 H ==> 2
2 D ==> 2
3 S ==> 3
3 C ==> 3
3 H ==> 3
3 D ==> 3
4 S ==> 4
4 C ==> 4
4 H ==> 4
4 D ==> 4
5 S ==> 5
5 C ==> 5
5 H ==> 5
5 D ==> 5
6 S ==> 6
6 C ==> 6
6 H ==> 6
6 D ==> 6
7 S ==> 7
7 C ==> 7
7 H ==> 7
7 D ==> 7
8 S ==> 8
8 C ==> 8
8 H ==> 8
8 D ==> 8
9 S ==> 9
9 C ==> 9
9 H ==> 9
9 D ==> 9
10 S ==> 10
10 C ==> 10
10 H ==> 10
10 D ==> 10
A S ==> 1
A C ==> 1
A H ==> 1
A D ==> 1
J S ==> 10
J C ==> 10
J H ==> 10
J D ==> 10
Q S ==> 10
Q C ==> 10
Q H ==> 10
Q D ==> 10
K S ==> 10
K C ==> 10
K H ==> 10
K D ==> 10


In [143]:
class Deck:
    def __init__(self, n_decks: int = 1):
        self.cards = []
        for i in range(n_decks):
            self._create_deck()

    def _create_deck(self):
        for surface in [str(x) for x in range(2, 11)] + ['A', 'J', 'Q', 'K']:
            for seed in ['C', 'H', 'S', 'C']:
                c = Card(surface = surface, seed = seed)
                self.cards.append(c)

    def shuffle(self):
        np.random.shuffle(self.cards)

    def deal(self, hand_size: int):
        hand = []
        for i in range(hand_size):
            try:
                hand.append(self.cards.pop())
            except IndexError:
                # raise IndexError('The deck is empty.')
                self._create_deck()
                hand.append(self.cards.pop()) # Instead of raising an error, we recreate the deck
        return hand

    @property # Allows to call size as deck.size and not deck.size()
    def size(self):
        return len(self.cards)

In [144]:
deck = Deck(5)
deck.size

260

In [145]:
deck.shuffle()
hand = deck.deal(10)
hand

[2 C, 6 C, 7 H, 3 C, J C, 2 S, Q C, 8 C, J S, 7 S]

In [146]:
sum(c.value() for c in hand) # The value of the hand

65

In [161]:
class BJCard(Card):
    
    @property
    def value(self):
        if self.surface in {'J', 'Q', 'K'}:
            return 10
        elif self.surface == 'A':
            return 11
        else:
            return int(self.surface)

In [162]:
class Deck:
    def __init__(self, n_decks: int = 1):
        self.cards = []
        for i in range(n_decks):
            self._create_deck()

    def _create_deck(self):
        for surface in [str(x) for x in range(2, 11)] + ['A', 'J', 'Q', 'K']:
            for seed in ['C', 'H', 'S', 'C']:
                c = BJCard(surface = surface, seed = seed) # Blackjack card
                self.cards.append(c)

    def shuffle(self):
        np.random.shuffle(self.cards)

    def deal(self, hand_size: int):
        hand = []
        for i in range(hand_size):
            try:
                hand.append(self.cards.pop())
            except IndexError:
                self._create_deck()
                hand.append(self.cards.pop())
        return hand

    @property
    def size(self):
        return len(self.cards)

In [163]:
c = Card(surface = 'A', seed = 'S')
b = BJCard(surface = 'A', seed = 'S')

print(c, c.value)
print(b, b.value)

A S 1
A S 11
